---
title: "Twitter Search"
author: "Charles Lang"
date: "February 3, 2016"
output: html_document
---
#Set OAuth
```{r}
library(ROAuth)
library(twitteR)

api_key <- "WSUiTcfEhw6cosz25uqrIMXjr"

api_secret <- "aflphctsNQgltOGupbZmd4GAmdUnhIkJkeAFcp570J3m53sUfn"

access_token <- "325558736-aAvV8qFqXJiWvghqdo5HB8Kbz7RboIMACaF13TVk"

access_token_secret <- "kbroUsysVDawjC3xrXJKXpBan3jdPLO0fHmj48ByL4n6h"

setup_twitter_oauth(api_key, api_secret, access_token, access_token_secret)
```
#Download Tweets
```{r}
T1 <- searchTwitter("#DSE16")
T1 <- do.call("rbind", lapply(T1, as.data.frame))
```
#Plot tweets
```{r}
#By name
counts=table(Tmerge$screenName)
barplot(counts, las=2)

#By time of day
hist(Tmerge$created, breaks = "d")
```
#Save file
```{r}
write.table(T1, "/Users/cwmlang_old/Desktop/Twitter_2-10-16.csv", sep = ",")
```
#Merge old-new file
```{r}
T2 <- read.table("/Users/cwmlang_old/Documents/NYU/EDCT2550/Github/Class-Data/Twitter_2-3-16.csv", sep = ",", header = TRUE)

Tmerge <- rbind(T1, T2)
Tmerge <- unique(Tmerge)

```

